#pragma once

#include <silex/abelian_group.hpp>
#include <silex/archimedean.hpp>
#include <silex/aut.hpp>
#include <silex/class_group.hpp>
#include <silex/diagnostics.hpp>
#include <silex/element.hpp>
#include <silex/embedding.hpp>
#include <silex/factor_base.hpp>
#include <silex/factored.hpp>
#include <silex/factored_element.hpp>
#include <silex/fmpz_smat.hpp>
#include <silex/hom.hpp>
#include <silex/ideal.hpp>
#include <silex/ideal_factorization.hpp>
#include <silex/lat.hpp>
#include <silex/number_field.hpp>
#include <silex/order.hpp>
#include <silex/order_element.hpp>
#include <silex/order_unit.hpp>
#include <silex/prime_ideal.hpp>
#include <silex/relation.hpp>
#include <silex/residue_field.hpp>
#include <silex/residue_ring.hpp>
#include <silex/signature.hpp>
#include <silex/status.hpp>
#include <silex/sunit.hpp>
#include <silex/unit.hpp>
#include <silex/version.hpp>
#include <silex/zeta.hpp>
